# Generated by Django 5.2.1 on 2025-06-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["email"], name="accounts_ot_email_265886_idx"),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["code"], name="accounts_ot_code_e43106_idx"),
        ),
    ]
